### ISSUE TITLE
Update the Remix example to Vite-based Remix

### ISSUE THREAD

**Issue by kettanaito** [mswjs/examples#117]
- Originates from https://github.com/mswjs/msw/discussions/1133#discussioncomment-9819596

**Comment by radiantbeing** [comment]
Hi. I’m writing this comment to help those trying to integrate MSW with a Vite-based Remix v2 project until this repository's example is updated. I will share my attempts to get the example working on a newly created Remix v2 project. Please note that I haven't tried integrating it with testing libraries yet.

1. Create a new Remix project with the latest version. At the time of writing, the latest version of Remix is 2.10.0.

    ```bash
    npx create-remix@latest
    ```

2. Install MSW.

    ```bash
    npm install msw@latest --save-dev
    ```

3. Initialize the worker script.

    ```bash
    npx msw init ./public
    ```

4. Copy the following files to the same paths in your newly created project:
    - [`app/mocks/browser.ts`](https://github.com/mswjs/examples/blob/5994f5654d1de37d31239d6cd96986a2ae940bb3/examples/with-remix/app/mocks/browser.ts)
    - [`app/mocks/handlers.ts`](https://github.com/mswjs/examples/blob/5994f5654d1de37d31239d6cd96986a2ae940bb3/examples/with-remix/app/mocks/handlers.ts)
    - [`app/mocks/node.ts`](https://github.com/mswjs/examples/blob/5994f5654d1de37d31239d6cd96986a2ae940bb3/examples/with-remix/app/mocks/node.ts)
    - [`app/routes/_index.tsx`](https://github.com/mswjs/examples/blob/5994f5654d1de37d31239d6cd96986a2ae940bb3/examples/with-remix/app/routes/_index.tsx)
    - [`app/entry.client.tsx`](https://github.com/mswjs/examples/blob/5994f5654d1de37d31239d6cd96986a2ae940bb3/examples/with-remix/app/entry.client.tsx)
    - [`app/entry.server.tsx`](https://github.com/mswjs/examples/blob/5994f5654d1de37d31239d6cd96986a2ae940bb3/examples/with-remix/app/entry.server.tsx)

5. Fix the errors in `app/entry.server.tsx`. You can find the modified `entry.server.tsx` [here](https://gist.github.com/radiantbeing/75d53e8f3eb6ba9b4e1026a5bb09294c).
    - Since Remix v2 has removed the `Response` polyfill module, you should use the global `Response`. Remove `import { Response } from "@remix-run/node";`.
    - Use the `createReadableStreamFromReadable` method from `@remix-run/node` to convert the body variable from Node’s `PassThrough` to a web `ReadableStream`.

        ```tsx
        import { createReadableStreamFromReadable } from "@remix-run/node";
        
        // ...
        resolve(
          new Response(createReadableStreamFromReadable(body), {
            headers: responseHeaders,
            status: responseStatusCode,
          })
        );
        // ...
        ```
        
    - `isbot` has changed to provide only named exports instead of a default export in the latest version. Wrap the module exported by `isbot` with {}.

        ```tsx
        import { isbot } from 'isbot';
        ```
        
6. Fix the errors in `app/routes/_index.tsx`. You can find the modified `_index.tsx` [here](https://gist.github.com/radiantbeing/fe1db522a744a1d31fb85c9b848c6d87).
    - Change `V2_MetaFunction` to `MetaFunction`.

        ```tsx
        import type { LoaderFunction, MetaFunction } from '@remix-run/node';
        // ...
        
        export const meta: MetaFunction = () => {
          // ...
        }
        ```
        
    - Add a generic to `useLoaderData`.

        ```tsx
        const { serverSideData } = useLoaderData<typeof loader>();
        ```
        
7. You’re done! Start the development server and check if the mocked data is fetched correctly.
    
    Since Tailwind's browser default style reset might make it difficult to distinguish elements, you can comment out `import "./tailwind.css";` in `app/root.tsx`.
    

I hope this helps. Please let me know if there are any parts that need improvement.

**Comment by radiantbeing** [comment]
Hi. I’m writing this comment to help those trying to integrate MSW with the latest version of a Vite-based Remix v2 project until this repository's example is updated. I will share my attempts to get the example working on a newly created Remix v2 project. Please note that I haven't tried integrating it with testing libraries yet.

1. Create a new Remix project with the latest version. At the time of writing, the latest version of Remix is 2.10.0.

    ```bash
    npx create-remix@latest
    ```

2. Install MSW.

    ```bash
    npm install msw@latest --save-dev
    ```

3. Initialize the worker script.

    ```bash
    npx msw init ./public
    ```

4. Copy the following files to the same paths in your newly created project:
    - [`app/mocks/browser.ts`](https://github.com/mswjs/examples/blob/5994f5654d1de37d31239d6cd96986a2ae940bb3/examples/with-remix/app/mocks/browser.ts)
    - [`app/mocks/handlers.ts`](https://github.com/mswjs/examples/blob/5994f5654d1de37d31239d6cd96986a2ae940bb3/examples/with-remix/app/mocks/handlers.ts)
    - [`app/mocks/node.ts`](https://github.com/mswjs/examples/blob/5994f5654d1de37d31239d6cd96986a2ae940bb3/examples/with-remix/app/mocks/node.ts)
    - [`app/routes/_index.tsx`](https://github.com/mswjs/examples/blob/5994f5654d1de37d31239d6cd96986a2ae940bb3/examples/with-remix/app/routes/_index.tsx)
    - [`app/entry.client.tsx`](https://github.com/mswjs/examples/blob/5994f5654d1de37d31239d6cd96986a2ae940bb3/examples/with-remix/app/entry.client.tsx)
    - [`app/entry.server.tsx`](https://github.com/mswjs/examples/blob/5994f5654d1de37d31239d6cd96986a2ae940bb3/examples/with-remix/app/entry.server.tsx)

5. Fix the errors in `app/entry.server.tsx`. You can find the modified `entry.server.tsx` [here](https://gist.github.com/radiantbeing/75d53e8f3eb6ba9b4e1026a5bb09294c).
    - Since Remix v2 has removed the `Response` polyfill module, you should use the global `Response`. Remove `import { Response } from "@remix-run/node";`.
    - Use the `createReadableStreamFromReadable` method from `@remix-run/node` to convert the body variable from Node’s `PassThrough` to a web `ReadableStream`.

        ```tsx
        import { createReadableStreamFromReadable } from "@remix-run/node";
        
        // ...
        resolve(
          new Response(createReadableStreamFromReadable(body), {
            headers: responseHeaders,
            status: responseStatusCode,
          })
        );
        // ...
        ```
        
    - `isbot` has changed to provide only named exports instead of a default export in the latest version. Wrap the module exported by `isbot` with {}.

        ```tsx
        import { isbot } from 'isbot';
        ```
        
6. Fix the errors in `app/routes/_index.tsx`. You can find the modified `_index.tsx` [here](https://gist.github.com/radiantbeing/fe1db522a744a1d31fb85c9b848c6d87).
    - Change `V2_MetaFunction` to `MetaFunction`.

        ```tsx
        import type { LoaderFunction, MetaFunction } from '@remix-run/node';
        // ...
        
        export const meta: MetaFunction = () => {
          // ...
        }
        ```
        
    - Add a generic to `useLoaderData`.

        ```tsx
        const { serverSideData } = useLoaderData<typeof loader>();
        ```
        
7. You’re done! Start the development server and check if the mocked data is fetched correctly.
    
    Since Tailwind's browser default style reset might make it difficult to distinguish elements, you can comment out `import "./tailwind.css";` in `app/root.tsx`.
    

I hope this helps. I would appreciate it if you could point out any mistakes.

**Comment by paulomenezes** [comment]
Hey @kettanaito have you already try msw with Remix and vite? I'm trying to run a Hydrogen project, that uses Remix, and it doesn't work: 

```
2:47:49 PM [vite] Pre-transform error: No known conditions for "./node" specifier in "msw" package
Error during module fetch: Error: No known conditions for "./node" specifier in "msw" package
    at e (file:///project-path/node_modules/.pnpm/vite@5.4.6_@types+node@22.5.5/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:45978:25)
    at n (file:///project-path/node_modules/.pnpm/vite@5.4.6_@types+node@22.5.5/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:45978:646)
    at o (file:///project-path/node_modules/.pnpm/vite@5.4.6_@types+node@22.5.5/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:45978:1297)
    at resolveExportsOrImports (file:///project-path/node_modules/.pnpm/vite@5.4.6_@types+node@22.5.5/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:46599:18)
    at resolveDeepImport (file:///project-path/node_modules/.pnpm/vite@5.4.6_@types+node@22.5.5/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:46622:25)
    at tryNodeResolve (file:///project-path/node_modules/.pnpm/vite@5.4.6_@types+node@22.5.5/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:46387:16)
    at ResolveIdContext.resolveId (file:///project-path/node_modules/.pnpm/vite@5.4.6_@types+node@22.5.5/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:46137:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PluginContainer.resolveId (file:///project-path/node_modules/.pnpm/vite@5.4.6_@types+node@22.5.5/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:48951:22)
    at async TransformPluginContext.resolve (file:///project-path/node_modules/.pnpm/vite@5.4.6_@types+node@22.5.5/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:49112:15)
    at async normalizeUrl (file:///project-path/node_modules/.pnpm/vite@5.4.6_@types+node@22.5.5/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:63976:26)
    at async file:///project-path/node_modules/.pnpm/vite@5.4.6_@types+node@22.5.5/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:64115:39
    at async Promise.all (index 0)
    at async TransformPluginContext.transform (file:///project-path/node_modules/.pnpm/vite@5.4.6_@types+node@22.5.5/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:64042:7)
    at async PluginContainer.transform (file:///project-path/node_modules/.pnpm/vite@5.4.6_@types+node@22.5.5/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:49033:18)
    at async loadAndTransform (file:///project-path/node_modules/.pnpm/vite@5.4.6_@types+node@22.5.5/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:51866:27)
    at async fetchModule (file:///project-path/node_modules/.pnpm/vite@5.4.6_@types+node@22.5.5/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:54413:16) {
  plugin: 'vite:import-analysis',
  id: '/project-path/app/mocks/node.ts',
  pluginCode: 'import { setupServer } from "msw/node";\n' +
    'import { handlers } from "~/app/mocks/handlers";\n' +
    'export const server = setupServer(...handlers);\n'
}
```

When I comment `server.listen();` from `entry.server.tsx`, the project works with the browser mocks, but the server doesn't work.

I also added this comment [here](https://github.com/mswjs/msw/discussions/1133#discussioncomment-10742569), not sure what is easy to track.

**Comment by unclejustin** [comment]
This also does not work if you have redirects in your app.

example:

```ts
import { redirect } from "@remix-run/node";

export const loader = async ({ request }: LoaderFunctionArgs) => {
  await getAuthenticatedData(request);
  return redirect("/home");
};
```


Throws: `Error: Redirects returned/thrown from loaders/actions must have a Location header`
