### ISSUE TITLE
thrown: "API not configured" error

### ISSUE THREAD

**Issue by artivilla** [mswjs/examples#69]
Might not be related directly to mswjs but switching from mocking fetch to msw introduced this. Running DEBUG=*, but unclear if the component is calling something that's not mocked:
```
  babel program.body[8].expression.arguments[1].body.body[1].expression.arguments[1].body.body[6].expression CallExpression: Recursing into... +0ms
  babel program.body[8].expression.arguments[1].body.body[1].expression.arguments[1].body.body[6].expression.callee MemberExpression: enter +0ms
  babel program.body[8].expression.arguments[1].body.body[1].expression.arguments[1].body.body[6].expression.callee MemberExpression: Recursing into... +0ms
  babel program.body[8].expression.arguments[1].body.body[1].expression.arguments[1].body.body[6].expression.callee.object CallExpression: enter +0ms
  babel program.body[8].expression.arguments[1].body.body[1].expression.arguments[1].body.body[6].expression.callee.object CallExpression: Recursing into... +0ms
  babel program.body[8].expression.arguments[1].body.body[1].expression.arguments[1].body.body[6].expression.callee.object.arguments[0] CallExpression: enter +0ms
  babel program.body[8].expression.arguments[1].body.body[1].expression.arguments[1].body.body[6].expression.callee.object.arguments[0] CallExpression: Recursing into... +0ms
  babel program.body[8].expression.arguments[1].body.body[1].expression.arguments[1].body.body[6].expression.callee.object.arguments[0].callee MemberExpression: enter +0ms
  babel program.body[8].expression.arguments[1].body.body[1].expression.arguments[1].body.body[6].expression.callee.object.arguments[0].callee MemberExpression: Recursing into... +0ms
  babel program.body[8].expression.arguments[1].body.body[1].expression.arguments[1].body.body[6].expression.callee.object.arguments[0].callee.object MemberExpression: enter +0ms
  babel program.body[8].expression.arguments[1].body.body[1].expression.arguments[1].body.body[6].expression.callee.object.arguments[0].callee.object MemberExpression: Recursing into... +0ms
  babel program.body[8].expression.arguments[1].body.body[1].expression.arguments[1].body.body[6].expression.callee.object.arguments[0].callee.object MemberExpression: exit +1ms
  babel program.body[8].expression.arguments[1].body.body[1].expression.arguments[1].body.body[6].expression.callee.object.arguments[0].callee MemberExpression: exit +0ms
  babel program.body[8].expression.arguments[1].body.body[1].expression.arguments[1].body.body[6].expression.callee.object.arguments[0].arguments[0] TemplateLiteral: enter +0ms
  babel program.body[8].expression.arguments[1].body.body[1].expression.arguments[1].body.body[6].expression.callee.object.arguments[0].arguments[0] TemplateLiteral: Recursing into... +0ms
  babel program.body[8].expression.arguments[1].body.body[1].expression.arguments[1].body.body[6].expression.callee.object.arguments[0].arguments[0] TemplateLiteral: exit +0ms
  babel program.body[8].expression.arguments[1].body.body[1].expression.arguments[1].body.body[6].expression.callee.object.arguments[0] CallExpression: exit +0ms
  babel program.body[8].expression.arguments[1].body.body[1].expression.arguments[1].body.body[6].expression.callee.object CallExpression: exit +0ms
  babel program.body[8].expression.arguments[1].body.body[1].expression.arguments[1].body.body[6].expression.callee MemberExpression: exit +0ms
  babel program.body[8].expression.arguments[1].body.body[1].expression.arguments[1].body.body[6].expression CallExpression: exit +0ms
  babel program.body[8].expression.arguments[1].body.body[1].expression.arguments[1].body.body[6] ExpressionStatement: exit +0ms
  babel program.body[8].expression.arguments[1].body.body[1].expression.arguments[1].body BlockStatement: exit +0ms
  babel program.body[8].expression.arguments[1].body.body[1].expression.arguments[1] ArrowFunctionExpression: exit +0ms
  babel program.body[8].expression.arguments[1].body.body[1].expression CallExpression: exit +0ms
  babel program.body[8].expression.arguments[1].body.body[1] ExpressionStatement: exit +0ms
  babel program.body[8].expression.arguments[1].body BlockStatement: exit +0ms
  babel program.body[8].expression.arguments[1] ArrowFunctionExpression: exit +0ms
  babel program.body[8].expression CallExpression: exit +0ms
  babel program.body[8] ExpressionStatement: exit +0ms
  http override patching "http" module... +0ms
  http override patching "https" module... +1ms
  XHR patching "XMLHttpRequest" module... +0ms
  http override restoring modules... +86ms
  XHR restoring modules... +86ms
 FAIL  src/widgets/help/__tests__/HelpPanel.tests.tsx
  ● HelpPanel and StaticHelpPanel › HelpPanel successfully renders articles & title given mocked data

    thrown: "API not configured"

      at _getError (node_modules/jest-circus/build/utils.js:566:18)
          at Array.map (<anonymous>)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:404:19)
```
The title of the component passes assertion but the data from the payload doesn't render. I would imagine it should hit these handlers:
```
export const handlers = [
    /* catch all */
    rest.get('*', (req, res, ctx) => {
        console.error(`Please add requst handler for ${req.url.toString()}`);
        return res(ctx.status(500), ctx.json({ error: 'Please add request handler' }));
    }),
    rest.post('*', (req, res, ctx) => {
        console.error(`Please add POST requst handler for ${req.url.toString()}`);
        return res(ctx.status(500), ctx.json({ error: 'Please add request handler' }));
    }),
];
```
I've mocked the server here:
```
        server.use(
            rest.post(appServerUrl('/api/v1/help/articles'), (req, res, { json }) => {
                return res(json(articleResponseJson));
            }),
        );
```

**Comment by kettanaito** [comment]
Based on the logs, your test process never reached MSW in the first place. Have you googled for this exact error? Maybe you're using new global `test` in Node and that's somehow not configured?

**Comment by artivilla** [comment]
Lol this is serious commitment. I would just close this issue, its too old but TY!
